{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1fe4837e",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Phase 2 post-processing: automated sample-code resolution.\n",
    "\n",
    "Problem: despite the prompt's code-resolution rule (rule 3), Luna still\n",
    "leaves bare local codes in `source`/`material`/`target` for a meaningful\n",
    "share of triples (e.g. \"TT\", \"SS\", \"PA\", \"PG\", \"PPI 1\", \"HP-20\"). These\n",
    "codes are meaningless outside the paper they came from and will not merge\n",
    "correctly in the knowledge graph.\n",
    "\n",
    "This script requires NO further API calls. It works entirely from data\n",
    "already in phase2_luna_full_triples.xlsx:\n",
    "\n",
    "  1. Flags rows whose source/material/target looks like a bare code\n",
    "     (all-caps abbreviation, code+digit, or code with a hyphenated suffix).\n",
    "  2. For each flagged row, looks at every OTHER row from the SAME chunk_id\n",
    "     (same paper, same chunk) to find a fully-resolved phrase that most\n",
    "     plausibly corresponds to the code -- using two signals:\n",
    "       a) the code appears as a parenthetical abbreviation inside another\n",
    "          row's source/material/target in the same chunk\n",
    "          (e.g. \"hemp seed protein isolate ultrafiltration (UF)\" defines UF)\n",
    "       b) the code appears verbatim inside another row's flagged_phrase\n",
    "          or corresponding_sentence in the same chunk, immediately preceded\n",
    "          by a resolved noun phrase\n",
    "  3. Writes a review file with every flagged row, its best-guess resolution,\n",
    "     and a confidence label, so you can spot-check before trusting it.\n",
    "  4. Writes a corrected copy of the triples table with resolved values\n",
    "     substituted in wherever a confident match was found, and leaves\n",
    "     everything else untouched.\n",
    "\n",
    "Nothing here calls the OpenAI or Gemini API. This is pure post-processing\n",
    "against your existing extraction output.\n",
    "\n",
    "Usage:\n",
    "    python resolve_sample_codes.py phase2_luna_full_triples.xlsx\n",
    "\"\"\"\n",
    "\n",
    "import re\n",
    "import sys\n",
    "from pathlib import Path\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Config\n",
    "# ---------------------------------------------------------------------------\n",
    "\n",
    "FIELDS_TO_CHECK = [\"source\", \"material\", \"target\"]\n",
    "\n",
    "# A field counts as a \"bare code\" if it matches any of these patterns and\n",
    "# is short enough that it's very unlikely to be a real descriptive phrase.\n",
    "CODE_PATTERNS = [\n",
    "    r\"^[A-Z]{2,6}$\",                     # TT, SS, CC, PA, GL, PG, HPP, DIC, SPU\n",
    "    r\"^[A-Z]{1,4}\\s?\\d{1,3}$\",           # PPI 1, PPI2, SP-4 (without hyphen), G5\n",
    "    r\"^[A-Z]{1,5}-\\d{1,3}$\",             # HP-20, SP-207\n",
    "    r\"^[A-Z]\\d{1,3}-[A-Z]{1,4}$\",        # G5-UF, G5-IP\n",
    "    r\"^[A-Z]{2,6}\\d{0,3}-[A-Z]{2,6}$\",   # NaCas-like compound codes, PPI-NaCas\n",
    "]\n",
    "CODE_RE = re.compile(\"|\".join(f\"(?:{p})\" for p in CODE_PATTERNS))\n",
    "\n",
    "# Common legitimate short chemical formulas / units to NEVER flag as codes,\n",
    "# since they're real, portable entities, not paper-local shorthand.\n",
    "KNOWN_SAFE = {\n",
    "    \"NaCl\", \"KCl\", \"CaCl2\", \"MgCl2\", \"NaOH\", \"HCl\", \"H2O2\", \"Na2SO4\",\n",
    "    \"NaSCN\", \"NaClO4\", \"NaI\", \"CO2\", \"GDL\", \"UV\", \"pH\", \"PBS\", \"SDS\",\n",
    "    \"DTT\", \"GABA\", \"ACE\",\n",
    "}\n",
    "\n",
    "\n",
    "def looks_like_code(value: str) -> bool:\n",
    "    if not isinstance(value, str) or not value.strip():\n",
    "        return False\n",
    "    v = value.strip()\n",
    "    if v in KNOWN_SAFE:\n",
    "        return False\n",
    "    # Must match a code pattern\n",
    "    if not CODE_RE.match(v):\n",
    "        return False\n",
    "    return True\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Resolution logic\n",
    "# ---------------------------------------------------------------------------\n",
    "\n",
    "def find_definition_in_text(code: str, text: str) -> str | None:\n",
    "    \"\"\"Look for a pattern like 'resolved phrase (CODE)' in the given text,\n",
    "    which is the standard way papers define an abbreviation on first use.\n",
    "    Returns the resolved phrase if found, else None.\n",
    "    \"\"\"\n",
    "    if not isinstance(text, str) or not text:\n",
    "        return None\n",
    "    # Escape code for regex safety (handles hyphens, digits)\n",
    "    escaped = re.escape(code)\n",
    "    # Pattern: some words immediately followed by \"(CODE)\"\n",
    "    pattern = rf\"([A-Za-z][A-Za-z0-9\\-\\s]{{3,80}}?)\\s*\\(\\s*{escaped}\\s*\\)\"\n",
    "    match = re.search(pattern, text)\n",
    "    if match:\n",
    "        phrase = match.group(1).strip()\n",
    "        # Trim leading connector words that sometimes get captured\n",
    "        phrase = re.sub(r\"^(the|a|an|and|or|with)\\s+\", \"\", phrase, flags=re.IGNORECASE)\n",
    "        return phrase\n",
    "    return None\n",
    "\n",
    "\n",
    "def resolve_code_for_chunk(code: str, chunk_rows: pd.DataFrame) -> tuple[str | None, str]:\n",
    "    \"\"\"Try to resolve `code` using every field of every row belonging to\n",
    "    the same chunk. Returns (resolved_phrase_or_None, confidence_label).\n",
    "    \"\"\"\n",
    "    search_fields = [\"source\", \"material\", \"target\", \"flagged_phrase\", \"corresponding_sentence\"]\n",
    "\n",
    "    # Pass 1: look for \"phrase (CODE)\" definition pattern - highest confidence\n",
    "    for _, row in chunk_rows.iterrows():\n",
    "        for field in search_fields:\n",
    "            text = row.get(field, \"\")\n",
    "            resolved = find_definition_in_text(code, text)\n",
    "            if resolved:\n",
    "                return resolved, \"high (explicit definition found)\"\n",
    "\n",
    "    # Pass 2: look for the code appearing as a substring inside a longer,\n",
    "    # non-code phrase in source/material/target from the same chunk\n",
    "    # (e.g. code \"SS\" appearing inside \"SS ingredient\" elsewhere, weak signal)\n",
    "    candidates = []\n",
    "    for _, row in chunk_rows.iterrows():\n",
    "        for field in [\"source\", \"material\", \"target\"]:\n",
    "            text = row.get(field, \"\")\n",
    "            if not isinstance(text, str):\n",
    "                continue\n",
    "            if code in text and text.strip() != code and not looks_like_code(text):\n",
    "                candidates.append(text.strip())\n",
    "    if candidates:\n",
    "        # Most frequent candidate wins\n",
    "        best = max(set(candidates), key=candidates.count)\n",
    "        return best, \"medium (co-occurrence match, verify manually)\"\n",
    "\n",
    "    return None, \"unresolved (no match found in chunk)\"\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------------\n",
    "# Main\n",
    "# ---------------------------------------------------------------------------\n",
    "\n",
    "def main():\n",
    "    if len(sys.argv) < 2:\n",
    "        print(\"Usage: python resolve_sample_codes.py <triples_file.xlsx>\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    in_path = Path(sys.argv[1])\n",
    "    df = pd.read_excel(in_path)\n",
    "    print(f\"Loaded {len(df)} triples from {in_path}\")\n",
    "\n",
    "    # Identify every row with a bare-code field\n",
    "    flagged_rows = []\n",
    "    for idx, row in df.iterrows():\n",
    "        for field in FIELDS_TO_CHECK:\n",
    "            val = row.get(field, \"\")\n",
    "            if looks_like_code(val):\n",
    "                flagged_rows.append({\"row_index\": idx, \"field\": field, \"code\": val.strip()})\n",
    "\n",
    "    print(f\"Found {len(flagged_rows)} bare-code field instances across \"\n",
    "          f\"{len(set(r['row_index'] for r in flagged_rows))} rows.\")\n",
    "\n",
    "    if not flagged_rows:\n",
    "        print(\"Nothing to resolve.\")\n",
    "        return\n",
    "\n",
    "    # Resolve each flagged instance using other rows from the same chunk\n",
    "    review_records = []\n",
    "    df_corrected = df.copy()\n",
    "\n",
    "    for item in flagged_rows:\n",
    "        idx = item[\"row_index\"]\n",
    "        field = item[\"field\"]\n",
    "        code = item[\"code\"]\n",
    "        chunk_id = df.at[idx, \"chunk_id\"]\n",
    "\n",
    "        chunk_rows = df[df[\"chunk_id\"] == chunk_id]\n",
    "        resolved, confidence = resolve_code_for_chunk(code, chunk_rows)\n",
    "\n",
    "        review_records.append({\n",
    "            \"row_index\": idx,\n",
    "            \"chunk_id\": chunk_id,\n",
    "            \"field\": field,\n",
    "            \"original_code\": code,\n",
    "            \"resolved_to\": resolved if resolved else \"\",\n",
    "            \"confidence\": confidence,\n",
    "            \"corresponding_sentence\": df.at[idx, \"corresponding_sentence\"]\n",
    "                if \"corresponding_sentence\" in df.columns else \"\",\n",
    "        })\n",
    "\n",
    "        # Only auto-apply high-confidence resolutions to the corrected copy.\n",
    "        # Medium-confidence matches are left in the review file for you to\n",
    "        # confirm before applying, since they're a weaker signal.\n",
    "        if resolved and confidence.startswith(\"high\"):\n",
    "            df_corrected.at[idx, field] = resolved\n",
    "\n",
    "    review_df = pd.DataFrame(review_records)\n",
    "    review_path = in_path.parent / f\"{in_path.stem}_code_resolution_review.xlsx\"\n",
    "    review_df.to_excel(review_path, index=False)\n",
    "    print(f\"Review file ({len(review_df)} flagged instances) -> {review_path}\")\n",
    "\n",
    "    n_high = (review_df[\"confidence\"].str.startswith(\"high\")).sum()\n",
    "    n_medium = (review_df[\"confidence\"].str.startswith(\"medium\")).sum()\n",
    "    n_unresolved = (review_df[\"confidence\"].str.startswith(\"unresolved\")).sum()\n",
    "    print(f\"  High confidence (auto-applied): {n_high}\")\n",
    "    print(f\"  Medium confidence (needs your review before applying): {n_medium}\")\n",
    "    print(f\"  Unresolved (needs manual lookup or a targeted re-extraction): {n_unresolved}\")\n",
    "\n",
    "    corrected_path = in_path.parent / f\"{in_path.stem}_code_resolved.xlsx\"\n",
    "    df_corrected.to_excel(corrected_path, index=False)\n",
    "    print(f\"Corrected triples (high-confidence fixes applied) -> {corrected_path}\")\n",
    "\n",
    "    print(\n",
    "        \"\\nNext step: open the review file, check the 'medium' confidence rows, \"\n",
    "        \"and if they look right, apply them manually or extend this script to \"\n",
    "        \"auto-apply medium-confidence matches above a chosen threshold.\"\n",
    "    )\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Shola-environment",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
