{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "19c73090",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Category taxonomy classifier: assigns each existing triple to exactly one\n",
    "of 11 closed categories, based only on fields already present in the\n",
    "Terra/Luna extraction output (source, source_type, target, target_type,\n",
    "interaction, material). No new API/LLM calls -- this is a rules-based\n",
    "pass over data you already have.\n",
    "\n",
    "Usage:\n",
    "    python classify_triple_categories.py phase2_terra_full_triples.xlsx\n",
    "\"\"\"\n",
    "\n",
    "import re\n",
    "import sys\n",
    "from pathlib import Path\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "COMPARISON_INTERACTIONS = {\"outperformed\", \"underperformed\", \"equivalent_to\"}\n",
    "PROPERTY_INTERACTIONS = {\"increased\", \"decreased\", \"induced\", \"exhibited\", \"no_significant_change\"}\n",
    "\n",
    "CULTIVAR_PATTERN = re.compile(\n",
    "    r\"(cultivar|genotype|variety|breeding line)\\b|'\\w+'\\s*(edamame|bean|seed)|\"\n",
    "    r\"\\bSP-\\d+\\b|\\bN\\d{2}[-–]\\d+\\b\",\n",
    "    re.IGNORECASE,\n",
    ")\n",
    "\n",
    "POLYSACCHARIDE_TERMS = re.compile(\n",
    "    r\"\\b(polysaccharide|gum|pectin|xanthan|dextran|maltodextrin|konjac|\"\n",
    "    r\"curdlan|alginate|carrageenan|cellulose|starch|glucomannan|\"\n",
    "    r\"glycosylation|glycation|maillard)\\b\",\n",
    "    re.IGNORECASE,\n",
    ")\n",
    "\n",
    "POLYPHENOL_TERMS = re.compile(\n",
    "    r\"\\b(polyphenol|catechin|phenolic|tannin|flavonoid|chlorogenic|\"\n",
    "    r\"anthocyanin|quercetin)\\b\",\n",
    "    re.IGNORECASE,\n",
    ")\n",
    "\n",
    "FRACTION_TERMS = re.compile(\n",
    "    r\"\\b(albumin|globulin|glutelin|prolamin|legumin|vicilin|edestin|\"\n",
    "    r\"7S|11S|beta-conglycinin|glycinin)\\b\",\n",
    "    re.IGNORECASE,\n",
    ")\n",
    "# A fraction name inside a ratio/ratio-like expression is a parameter, not\n",
    "# the fraction itself being the studied entity (e.g. \"legumin-to-vicilin\n",
    "# ratio\", \"legumin/vicilin ratio\") -- exclude these from protein_fraction.\n",
    "FRACTION_RATIO_PATTERN = re.compile(r\"\\bratios?\\b|\\bproportions?\\b\", re.IGNORECASE)\n",
    "\n",
    "COMMERCIAL_TERM = re.compile(r\"\\bcommercial\\b\", re.IGNORECASE)\n",
    "\n",
    "# Compound-source detection for protein_protein_blend: requires an explicit\n",
    "# \"and\"/\"blend\"/\"mixture\" connector joining two DISTINCT named materials,\n",
    "# not just any hyphen or \"with\" in the string (which fired on unrelated\n",
    "# single-material descriptors like \"acid-soluble\", \"dry-fractionated\").\n",
    "BLEND_CONNECTOR_PATTERN = re.compile(\n",
    "    r\"\\b\\w+(?:\\s+protein)?(?:\\s+isolate|\\s+concentrate)?\\s+(and|blend|mixture)\\s+\\w+\",\n",
    "    re.IGNORECASE,\n",
    ")\n",
    "COMBINED_MARKER = re.compile(r\"\\bcombined\\b|\\band\\b\", re.IGNORECASE)\n",
    "\n",
    "MATERIAL_TYPE = \"material_used_directly\"\n",
    "TREATMENT_TYPES = {\"modification_method\", \"extraction_method\"}\n",
    "\n",
    "\n",
    "def classify_row(row, chunk_context: dict = None) -> str:\n",
    "    \"\"\"Classify a single triple. `chunk_context`, if provided, maps\n",
    "    chunk_id -> a dominant-subject summary for that chunk, used to resolve\n",
    "    ambiguous rows (like a fraction ratio) using the chunk's actual\n",
    "    broader subject rather than the isolated row.\n",
    "    \"\"\"\n",
    "    source = str(row.get(\"source\", \"\") or \"\")\n",
    "    target = str(row.get(\"target\", \"\") or \"\")\n",
    "    material = str(row.get(\"material\", \"\") or \"\")\n",
    "    interaction = str(row.get(\"interaction\", \"\") or \"\")\n",
    "    source_type = str(row.get(\"source_type\", \"\") or \"\")\n",
    "    target_type = str(row.get(\"target_type\", \"\") or \"\")\n",
    "    chunk_id = row.get(\"chunk_id\", \"\")\n",
    "\n",
    "    if CULTIVAR_PATTERN.search(source) or CULTIVAR_PATTERN.search(target):\n",
    "        return \"cultivar_genotype_comparison\"\n",
    "\n",
    "    if interaction in COMPARISON_INTERACTIONS and (\n",
    "        COMMERCIAL_TERM.search(source) or COMMERCIAL_TERM.search(target)\n",
    "    ):\n",
    "        return \"commercial_protein_comparison\"\n",
    "\n",
    "    if interaction in COMPARISON_INTERACTIONS:\n",
    "        source_is_treatment = source_type in TREATMENT_TYPES\n",
    "        target_is_treatment = target_type in TREATMENT_TYPES\n",
    "        source_is_material = source_type == MATERIAL_TYPE\n",
    "        target_is_material = target_type == MATERIAL_TYPE\n",
    "\n",
    "        if source_is_treatment or target_is_treatment:\n",
    "            return \"treatment_comparison\"\n",
    "        if source_is_material and target_is_material:\n",
    "            return \"protein_protein_comparison\"\n",
    "        return \"uncategorized\"\n",
    "\n",
    "    if BLEND_CONNECTOR_PATTERN.search(source) and source_type == MATERIAL_TYPE:\n",
    "        if not POLYSACCHARIDE_TERMS.search(source) and not POLYPHENOL_TERMS.search(source):\n",
    "            if not FRACTION_RATIO_PATTERN.search(source):\n",
    "                return \"protein_protein_blend\"\n",
    "\n",
    "    if POLYSACCHARIDE_TERMS.search(source) or POLYSACCHARIDE_TERMS.search(target):\n",
    "        return \"protein_polysaccharide_conjugation\"\n",
    "\n",
    "    if source_type == \"modification_method\" and COMBINED_MARKER.search(source):\n",
    "        if not POLYSACCHARIDE_TERMS.search(source) and not POLYPHENOL_TERMS.search(source):\n",
    "            return \"protein_protein_conjugation\"\n",
    "\n",
    "    # Polyphenol complex: the polyphenol must be acting AS the source (the\n",
    "    # complexing/binding agent), not merely appearing as a measured target\n",
    "    # property (e.g. \"total phenolic content\" as an outcome is not the\n",
    "    # same relationship as \"walnut pellicle polyphenols induced X\").\n",
    "    if POLYPHENOL_TERMS.search(source):\n",
    "        return \"protein_polyphenol_complex\"\n",
    "\n",
    "    # Fraction terms (INCLUDING ratio/proportion expressions like\n",
    "    # \"legumin-to-vicilin ratio\" -- a ratio between two fractions IS a\n",
    "    # fraction-level measurement, not a reason to exclude it). But a ratio\n",
    "    # row can also be explaining a DIFFERENT chunk's real subject (e.g. a\n",
    "    # cultivar comparison chunk that mentions the ratio only to explain\n",
    "    # why one cultivar behaves differently) -- when chunk_context says the\n",
    "    # chunk is cultivar-dominant, defer to that instead, since the row in\n",
    "    # isolation cannot tell us which is true.\n",
    "    if FRACTION_TERMS.search(material) or FRACTION_TERMS.search(target) or FRACTION_TERMS.search(source):\n",
    "        if chunk_context is not None:\n",
    "            ctx = chunk_context.get(chunk_id, {})\n",
    "            if ctx.get(\"cultivar_dominant\", False):\n",
    "                return \"cultivar_genotype_comparison\"\n",
    "        return \"protein_fraction\"\n",
    "\n",
    "    if interaction in PROPERTY_INTERACTIONS:\n",
    "        return \"single_treatment_property_change\"\n",
    "\n",
    "    return \"uncategorized\"\n",
    "\n",
    "\n",
    "def build_chunk_context(df: pd.DataFrame) -> dict:\n",
    "    \"\"\"Pre-scan every chunk to determine its dominant subject, used to\n",
    "    resolve ambiguous rows (like fraction ratios) against what the chunk\n",
    "    is actually mostly about, not the isolated row. A chunk counts as\n",
    "    \"cultivar_dominant\" if at least a third of ITS rows show explicit\n",
    "    cultivar/genotype naming in source or target -- conservative on\n",
    "    purpose, so one stray cultivar mention doesn't override an otherwise\n",
    "    fraction-focused chunk.\n",
    "    \"\"\"\n",
    "    context = {}\n",
    "    for chunk_id, group in df.groupby(\"chunk_id\"):\n",
    "        n_rows = len(group)\n",
    "        cultivar_hits = 0\n",
    "        for _, r in group.iterrows():\n",
    "            s = str(r.get(\"source\", \"\") or \"\")\n",
    "            t = str(r.get(\"target\", \"\") or \"\")\n",
    "            if CULTIVAR_PATTERN.search(s) or CULTIVAR_PATTERN.search(t):\n",
    "                cultivar_hits += 1\n",
    "        context[chunk_id] = {\n",
    "            \"cultivar_dominant\": n_rows > 0 and (cultivar_hits / n_rows) >= 0.15\n",
    "            # Threshold lowered from 1/3 to 0.15 after checking real data:\n",
    "            # genuinely cultivar-focused chunks sat at 17-31% cultivar-hit\n",
    "            # rate, since most rows describe a measured property rather\n",
    "            # than repeating the cultivar name on every row.\n",
    "        }\n",
    "    return context\n",
    "\n",
    "\n",
    "def main():\n",
    "    if len(sys.argv) < 2:\n",
    "        print(\"Usage: python classify_triple_categories.py <triples_file.xlsx>\")\n",
    "        sys.exit(1)\n",
    "\n",
    "    in_path = Path(sys.argv[1])\n",
    "    df = pd.read_excel(in_path)\n",
    "    print(f\"Loaded {len(df)} triples from {in_path}\")\n",
    "\n",
    "    df = df.copy()\n",
    "    chunk_context = build_chunk_context(df)\n",
    "    df[\"category\"] = df.apply(lambda row: classify_row(row, chunk_context), axis=1)\n",
    "\n",
    "    counts = df[\"category\"].value_counts()\n",
    "    print(\"\\nCategory distribution:\")\n",
    "    print(counts.to_string())\n",
    "    print(f\"\\nUncategorized: {counts.get('uncategorized', 0)} \"\n",
    "          f\"({counts.get('uncategorized', 0) / len(df) * 100:.1f}%)\")\n",
    "\n",
    "    out_path = in_path.parent / f\"{in_path.stem}_categorized.xlsx\"\n",
    "    df.to_excel(out_path, index=False)\n",
    "    print(f\"\\nCategorized triples -> {out_path}\")\n",
    "\n",
    "    sample_rows = []\n",
    "    for cat in df[\"category\"].unique():\n",
    "        sample_rows.append(df[df[\"category\"] == cat].head(5))\n",
    "    sample_df = pd.concat(sample_rows, ignore_index=True)\n",
    "    sample_path = in_path.parent / f\"{in_path.stem}_category_samples.xlsx\"\n",
    "    sample_df.to_excel(sample_path, index=False)\n",
    "    print(f\"Spot-check samples (5 per category) -> {sample_path}\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Shola-environment",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
